{% set name = "pixy" %}
{% set version = "0.93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ksamuk/pixy/archive/{{ version }}.tar.gz
  sha256: 1b795cc2dbee66de7029e3ba951f7d659bd7825fcfc076c88658a0c17ca63c65

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv; conda install --yes -c bioconda tabix"
  skip: True  # [win or py<36]
  entry_points:
    - pixy = pixy.__main__:main

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - scikit-allel
    - pandas
    - numpy
    - zarr
    - python

test:
  commands:
    - pixy --help

about:
  home: https://github.com/ksamuk/pixy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Unbiased estimation of nucleotide diversity within and between populations'
  description: |
    pixy is a command-line tool for painlessly and correctly estimating 
    average nucleotide diversity within (π) and between (dxy) populations from a VCF. 
    In particular, pixy facilitates the use of VCFs containing invariant (AKA monomorphic) 
    sites AND tracks missing data, which are both essential for the correct computation of π and dxy.
  dev_url: https://github.com/ksamuk/pixy
  doc_url: https://pixy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/ksamuk/pixy/blob/master/README.md
  
extra:
  recipe-maintainers:
    - ksamuk
