{% set name = "pixy" %}
{% set version = "2.0.0.beta2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ksamuk/pixy/archive/{{ version }}.tar.gz
  sha256: 301b71147536ab473627f87bf470c3aa4525b8aae347c03f7f524d6ef6d44653

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  entry_points:
    - pixy = pixy.__main__:main

requirements:
  build:
    # Support for osx_arm64 as per
    # https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock
    - python >=3.8,<3.12                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - poetry                                 # [build_platform != target_platform]
  host:
    - python >=3.8,<3.12
    - poetry 
    - pip
    - setuptools
    - numpy
  run:
    - python >=3.8,<3.12
    - scikit-allel
    - pandas
    - numpy
    - poetry 
    - multiprocess
    - scipy
    - numcodecs

test:
  commands:
    - pixy --version

about:
  home: https://github.com/ksamuk/pixy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Unbiased estimation of nucleotide diversity within and between populations
  description: |
    pixy is a command-line tool for painlessly and correctly estimating 
    average nucleotide diversity within (π) and between (dxy) populations from a VCF. 
    In particular, pixy facilitates the use of VCFs containing invariant (AKA monomorphic) 
    sites, which are essential for the correct computation of π and dxy.
  dev_url: https://github.com/ksamuk/pixy
  doc_url: https://pixy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/ksamuk/pixy/blob/master/README.md

extra:
  recipe-maintainers:
    - ksamuk
